# This workflow will run every time a new release is created.
# It will first build the plugin using Maven, then publish it to GitHub packages and finally attach the artifacts to the release

name: Maven build and deploy on release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup workspace
      run: mkdir artifacts

    - name: Build with Maven
      run: |
        mvn -B clean install --file pom.xml
        cp BadRabbit-Bukkit/target/BadRabbit*.jar artifacts/
        cp BadRabbit-Bungee/target/BadRabbit*.jar artifacts/

    - name: Publish to GitHub Packages Apache Maven
      run: 'mvn deploy -pl BadRabbit-Bukkit,BadRabbit-Bungee -s $GITHUB_WORKSPACE/settings.xml "-DaltDeploymentRepository=github::default::https://maven.pkg.github.com/GeorgH93/BadRabbit"'
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'artifacts/*.jar'
